import {
  CalendarDaysIcon,
  HeartIcon,
  MoonIcon,
  ScaleIcon,
} from "@heroicons/vue/24/outline";
import {
  Apple,
  Bicycle,
  Chicken,
  FirstAidKit,
  Goblet,
  Guide,
  KnifeFork,
  Mug,
  NoSmoking,
  Soccer,
  Sugar,
} from "@element-plus/icons-vue";

const interests = [
  {
    id: 1,
    name: "Sleep",
    unit: "h",
    icon: MoonIcon,
    fg: "text-violet-600",
    bg: "bg-violet-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M | F",
  },
  {
    id: 2,
    name: "Nutrition",
    unit: "kcal",
    icon: KnifeFork,
    fg: "text-amber-400",
    bg: "bg-amber-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M",
  },
  {
    id: 3,
    name: "Heart Rate",
    unit: "bpm",
    icon: HeartIcon,
    fg: "text-red-600",
    bg: "bg-red-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M | F",
  },
  {
    id: 4,
    name: "Water",
    unit: "l",
    icon: Mug,
    fg: "text-sky-500",
    bg: "bg-sky-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M",
  },
  {
    id: 5,
    name: "Weight",
    unit: "kg",
    icon: ScaleIcon,
    fg: "text-gray-400",
    bg: "bg-gray-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M",
  },
  {
    id: 6,
    name: "Temperature",
    unit: "°C",
    icon: FirstAidKit,
    fg: "text-red-400",
    bg: "bg-red-50",
    category: "Health",
    categoryIcon: HeartIcon,
    categoryColor: "fill-red-500",
    origin: "M | F",
  },
  {
    id: 7,
    name: "Meat Free",
    unit: "d",
    icon: Chicken,
    fg: "text-amber-400",
    bg: "bg-amber-50",
    category: "Tracker",
    categoryIcon: CalendarDaysIcon,
    categoryColor: "fill-sky-500",
    origin: "M",
  },
  {
    id: 8,
    name: "Alcohol Free",
    unit: "d",
    icon: Goblet,
    fg: "text-red-500",
    bg: "bg-red-50",
    category: "Tracker",
    categoryIcon: CalendarDaysIcon,
    categoryColor: "fill-sky-500",
    origin: "M",
  },
  {
    id: 9,
    name: "Sugar Free",
    unit: "d",
    icon: Sugar,
    fg: "text-amber-400",
    bg: "bg-amber-50",
    category: "Tracker",
    categoryIcon: CalendarDaysIcon,
    categoryColor: "fill-sky-500",
    origin: "M",
  },
  {
    id: 10,
    name: "Vegan",
    unit: "d",
    icon: Apple,
    fg: "text-lime-400",
    bg: "bg-lime-50",
    category: "Tracker",
    categoryIcon: CalendarDaysIcon,
    categoryColor: "fill-sky-500",
    origin: "M",
  },
  {
    id: 11,
    name: "Smoke Free",
    unit: "d",
    icon: NoSmoking,
    fg: "text-amber-400",
    bg: "bg-amber-50",
    category: "Tracker",
    categoryIcon: CalendarDaysIcon,
    categoryColor: "fill-sky-500",
    origin: "M",
  },
  {
    id: 12,
    name: "Activity",
    unit: "h",
    icon: Bicycle,
    fg: "text-blue-400",
    bg: "bg-blue-50",
    category: "Fitness",
    categoryIcon: Soccer,
    categoryColor: "text-amber-500",
    origin: "M | F",
  },
  {
    id: 13,
    name: "Distance",
    unit: "km",
    icon: Guide,
    fg: "text-teal-400",
    bg: "bg-teal-50",
    category: "Fitness",
    categoryIcon: Soccer,
    categoryColor: "text-amber-500",
    origin: "M | F",
  },
];

export default interests;
